import { Providers } from "./providers";
import Header from "./layouts/Header";
import "./globals.css";

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <main className="max-w-[1280px] mx-auto py px-6">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
