export const metadata = {
  title: "About Map",
  description: "Generated by create next app",
};
import SectionAbout from "../components/Sections/SectionAbout";

export default function AboutPage() {
  return (
    <div>
      <SectionAbout />
    </div>
  );
}
