import { Providers } from "./providers";
import Header from "./layouts/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.lang}>
      <body>
        <Providers>
          <Header params={params} />
          <main className="max-w-[1024px] mx-auto">{children}</main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
