import { Providers } from "./providers";
import Header from "./layouts/Header";
import "./globals.css";

export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.lang}>
      <Providers>
        <body>
          <Header params={params} />
          <main className="max-w-[1024px] mx-auto">{children}</main>
          <footer></footer>
        </body>
      </Providers>
    </html>
  );
}
