// import "/app/layout.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keyword: "HIIIh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vn">
      <body>
        <header>HEADER</header>
        {children}
        <footer>FOOTER</footer>
      </body>
    </html>
  );
}
