import AuthProvider from "./components/AuthProvider";
import NavMenu from "./components/NavMenu";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";
import Test from "./components/Test";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <Providers>
            <NavMenu />
            <main className="max-w-[1024px] mx-auto">{children}</main>
          </Providers>
        </body>
      </AuthProvider>
    </html>
  );
}
